version: '3.5'
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    restart: always
    networks:
      - tailscale-net
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY= #type your authentication key here.
      - TS_ROUTES=192.168.5.0/24 #change it to your local network like 192.168.1.0/24 or 192.168.2.0/24, etc....
      - TS_STATE_DIR=/var/lib
      - TS_EXTRA_ARGS=--advertise-exit-node #if you want to enable this setting, remember to enable exit node in the tailscale login website also.
      - TS_HOSTNAME=Cute_cat #change it to any name that you want to show on the tailscale website machine tab.
      - TS_NO_LOGS_NO_SUPPORT=true
    volumes:
      - ./tailscale:/var/lib
      - ./tailscale/dev/net/tun:/dev/net/tun


networks:
  tailscale-net:
    name: tailscale-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.0.0/24
